### ISSUE TITLE
Issue with demoImg

### ISSUE THREAD

**Issue by sharathchandra92** [shiaokai/plex#4]
I get the following error:

> > demoImg
> > Undefined function 'getPrmDflt' for input arguments of type 'cell'.

Error in charDet (line 26)
[ss,minH,maxH,thr] = getPrmDflt(varargin,dfs,1);

Error in wordSpot (line 40)
t1S=tic; bbs=charDet(I,fModel,frnPrms); t1=toc(t1S);

Error in demoImg (line 35)
tic; words=wordSpot(I,lexS,fModel,wordSvm,[],{'minH',.04}); toc

**Comment by sharathchandra92** [comment]
Resolved. Had to install prerequisites! Apologies!

**Comment by MarouaTounsi** [comment]
Please, I get the same error.

Error: can't read model: number of return field is not correct
Index exceeds matrix dimensions.

Error in wordNms (line 40)
for j=1:length(words), words(j).bb(:,5)=py(j); end

Error in wordSpot (line 50)
words=wordNms(words,wordSvm);

Error in demoSvt (line 47)
tic; words=wordSpot(I,lexS,fModel,wordSvm); toc

Can anyone help me please. Thanks in advance.
